- name: Test Windows
  hosts: windows
  gather_facts: no

  tasks:
    - name: Ejecutar ipconfig
      ansible.windows.win_command:
        cmd: ipconfig

    - name: Win ping
      ansible.windows.win_ping:
